# ──────────────────────────────────────────────────────────────────────────────
# SAMPLE OUTPUT — For reference only. Not a real ticket.
# Generated by: generate-gherkin skill
# Demonstrates: feature structure, tagging, positive/negative/edge/security/a11y
# ──────────────────────────────────────────────────────────────────────────────

@UI @SAMPLE-101
Feature: MACA Document Generation with VIN / Chassis Number Support
  As an Admin or Manager
  I want to generate MACA documents that correctly display VIN or Chassis numbers
  So that vehicle identification documents are accurate and compliant

  Background:
    Given the application is accessible at "${APP_URL}"
    And the user is logged in as "Admin"
    And at least one vehicle record exists in the system

  # ── Positive Scenarios ──────────────────────────────────────────────────────

  @Smoke @Positive @HighPriority @AC-1 @SAMPLE-101
  Scenario: Admin generates MACA document and VIN number appears when Chassis is absent
    Given a vehicle record exists with VIN "1HGBH41JXMN109186" and no Chassis Number
    When the Admin navigates to the "Generate Document" page for the vehicle
    And the Admin clicks the "Generate MACA" button
    Then the system generates and displays the MACA document
    And the document shows "VIN No: 1HGBH41JXMN109186" below the "Year Model" field
    And the "Engine No / Chassis No" section is hidden from the document

  @Regression @Positive @HighPriority @AC-2 @SAMPLE-101
  Scenario: Admin generates MACA document and Chassis Number appears when VIN is absent
    Given a vehicle record exists with Chassis Number "CH1234567890" and no VIN Number
    When the Admin navigates to the "Generate Document" page for the vehicle
    And the Admin clicks the "Generate MACA" button
    Then the system generates and displays the MACA document
    And the document shows "Chassis No: CH1234567890" below the "Year Model" field
    And the "VIN No" section is hidden from the document

  @Regression @Positive @MediumPriority @AC-3 @SAMPLE-101 @AsManager
  Scenario: Manager can generate MACA document with the same VIN/Chassis logic
    Given the user is logged in as "Manager"
    And a vehicle record exists with VIN "2T1BURHE0JC043821" and no Chassis Number
    When the Manager navigates to the "Generate Document" page for the vehicle
    And the Manager clicks the "Generate MACA" button
    Then the system generates and displays the MACA document
    And the document shows "VIN No: 2T1BURHE0JC043821"

  @Regression @Positive @MediumPriority @AC-4 @SAMPLE-101
  Scenario: System displays Chassis Number when both VIN and Chassis are populated
    Given a vehicle record exists with VIN "1HGBH41JXMN109186" and Chassis Number "CH9876543210"
    When the Admin generates the MACA document for the vehicle
    Then the document shows "Chassis No: CH9876543210"
    And the "VIN No" section is hidden from the document

  # ── Negative Scenarios ──────────────────────────────────────────────────────

  @Negative @Regression @HighPriority @AC-5 @SAMPLE-101
  Scenario: System prevents document generation when both VIN and Chassis fields are empty
    Given a vehicle record exists with no VIN Number and no Chassis Number
    When the Admin navigates to the "Generate Document" page for the vehicle
    And the Admin clicks the "Generate MACA" button
    Then the system displays the error "Vehicle identification is required. Enter either a VIN Number or Chassis Number."
    And the MACA document is not generated

  @Negative @Regression @HighPriority @SAMPLE-101
  Scenario Outline: System rejects invalid VIN number formats
    Given a vehicle record exists with VIN "<invalid_vin>" and no Chassis Number
    When the Admin attempts to save the VIN number
    Then the system displays the validation error "<expected_error>"
    And the vehicle record is not saved

    Examples:
      | invalid_vin              | expected_error                                  |
      |                          | VIN Number is required                          |
      | ABC                      | VIN must be exactly 17 characters               |
      | 1HGBH41JXMN1091861       | VIN must be exactly 17 characters               |
      | 1HGBH41JXMN10918O        | VIN must not contain the letters I, O, or Q     |
      | <script>alert(1)</script> | VIN contains invalid characters                 |

  @Negative @Regression @MediumPriority @AC-5 @SAMPLE-101 @AsManager
  Scenario: Read-Only User cannot generate MACA documents
    Given the user is logged in as "Read-Only User"
    When the Read-Only User navigates to the "Generate Document" page
    Then the "Generate MACA" button is not visible or is disabled
    And the system displays "You do not have permission to generate documents"

  # ── Edge Cases ──────────────────────────────────────────────────────────────

  @EdgeCase @Regression @MediumPriority @SAMPLE-101
  Scenario Outline: System handles boundary-length inputs for VIN field
    Given the Admin is on the vehicle record editing page
    When the Admin enters a VIN of exactly "<length>" characters: "<vin_value>"
    And the Admin clicks "Save"
    Then the system <expected_outcome>

    Examples:
      | length | vin_value           | expected_outcome                                    |
      | 16     | 1HGBH41JXMN10918    | displays "VIN must be exactly 17 characters"        |
      | 17     | 1HGBH41JXMN109186   | saves the record successfully                       |
      | 18     | 1HGBH41JXMN1091861  | displays "VIN must be exactly 17 characters"        |
      | 0      |                     | displays "VIN Number is required"                   |

  @EdgeCase @Regression @MediumPriority @SAMPLE-101
  Scenario: System handles document generation when user double-clicks Generate button
    Given a vehicle record exists with VIN "1HGBH41JXMN109186"
    When the Admin double-clicks the "Generate MACA" button rapidly
    Then only one MACA document is generated
    And the "Generate MACA" button is disabled after the first click
    And the system displays a single success confirmation

  @EdgeCase @Regression @LowPriority @SAMPLE-101
  Scenario: System preserves form state when browser is refreshed during editing
    Given the Admin is editing a vehicle record
    And the Admin has entered "1HGBH41JXMN109186" in the "VIN Number" field
    When the Admin refreshes the browser page
    Then the system prompts "You have unsaved changes. Are you sure you want to leave?"
    And if the Admin confirms, the unsaved data is discarded

  @EdgeCase @Regression @MediumPriority @SAMPLE-101
  Scenario: System handles special characters gracefully in Chassis Number field
    Given the Admin is on the vehicle record editing page
    When the Admin enters "CH-1234/567.890" in the "Chassis Number" field
    And the Admin clicks "Save"
    Then the system either accepts or clearly rejects the input with an appropriate validation message
    And the system does not throw an unhandled error

  # ── Security Scenarios ──────────────────────────────────────────────────────

  @Security @Regression @HighPriority @SAMPLE-101
  Scenario: Unauthenticated user cannot access the document generation page
    Given the user is not logged in
    When the user navigates directly to the document generation URL
    Then the system redirects the user to the login page
    And no document data is exposed in the HTTP response

  @Security @Regression @HighPriority @SAMPLE-101 @AsManager
  Scenario: Guest user cannot escalate privileges to generate documents
    Given the user is logged in as "Guest"
    When the user sends a direct API request to the document generation endpoint
    Then the API returns HTTP status 403
    And the response body contains "Forbidden"
    And no document is generated in the system

  @Security @Regression @HighPriority @SAMPLE-101
  Scenario: System sanitizes XSS input in VIN field
    Given the Admin is on the vehicle record editing page
    When the Admin enters "<img src=x onerror=alert(1)>" in the "VIN Number" field
    And the Admin submits the form
    Then the system displays "VIN contains invalid characters"
    And no script is executed in the browser
    And the input is not stored in the database

  # ── Accessibility Scenarios ─────────────────────────────────────────────────

  @Accessibility @Regression @MediumPriority @SAMPLE-101
  Scenario: VIN Number and Chassis Number fields are fully keyboard accessible
    Given the Admin is on the vehicle record editing page
    When the Admin navigates the form using the Tab key only
    Then the "VIN Number" field receives focus in logical order
    And the "Chassis Number" field receives focus in logical order
    And the "Generate MACA" button is reachable and activatable via keyboard

  @Accessibility @Regression @MediumPriority @SAMPLE-101
  Scenario: Validation errors are announced to screen reader users
    Given the Admin is on the vehicle record editing page
    And the Admin leaves both VIN and Chassis fields empty
    When the Admin submits the form
    Then the validation error message has role="alert" or aria-live="assertive"
    And the error message text is descriptive and announces which field has the issue

  @Accessibility @Regression @LowPriority @SAMPLE-101
  Scenario: MACA document generation page meets WCAG 2.1 AA color contrast
    Given the Admin is on the "Generate Document" page
    When the page is inspected for accessibility
    Then all text elements have a color contrast ratio of at least 4.5:1
    And all interactive elements have a focus ring visible at a 3:1 contrast ratio
