# Feature: Registration Form — Instruction Section
# Generated by: Generate Test Cases Skill (Playwright-Test-Planner + Jira)
# Jira Ticket: BDBP1-202 — Registration Form: Instruction Section
# Application: https://bankofstlucia--digitalqa.sandbox.my.site.com/
# Generated: 2026-05-16
# AC Coverage: 19 of 19 acceptance criteria covered

Feature: Registration Form - Instruction Section

  Background:
    Given the user navigates to "https://bankofstlucia--digitalqa.sandbox.my.site.com/"
    And the user clicks "Start Application"
    And the user selects "New Customer"
    And the user selects "Bank Accounts" then "Ordinary Savings"
    And the user clicks "Continue"
    Then the user is on the Instruction Section page

  # =============================================
  # SMOKE — POSITIVE SCENARIOS
  # =============================================

  @Smoke @P0 @BDBP1-202 @JiraAC-03 @PageLoad
  Scenario: Instruction Section loads with all required content after product selection
    Given the user is on the Instruction Section page
    Then the heading "Ordinary Savings Application" should be visible
    And the "General Instructions" section should be visible
    And the "Important Compliance Notice" heading should be visible
    And the FATCA hyperlink should be visible
    And 4 residency-type accordion buttons should be present
    And the "Continue" button should be visible and enabled
    And the left sidebar should show "Instructions" as the active step

  @Smoke @P0 @BDBP1-202 @JiraAC-05 @Buttons
  Scenario: All four residency-type accordion buttons are present with correct labels
    Given the user is on the Instruction Section page
    Then the following accordion buttons should be visible:
      | Button Label |
      | Individual (National) of ECCU Territories |
      | Resident Nationals of CARICOM (except ECCU territories) |
      | Non-Nationals / Residents Outside CARICOM |
      | Self – Employed Individuals |
    And all 4 buttons should be in a collapsed state

  @Smoke @P0 @BDBP1-202 @JiraAC-04 @JiraAC-DOD-02 @FATCA
  Scenario: FATCA compliance notice is present with a working hyperlink to IRS.gov
    Given the user is on the Instruction Section page
    When the user locates the "Important Compliance Notice" section
    Then the compliance text should mention U.S. citizens and residents
    And a hyperlink "FATCA (Foreign Account Tax Compliance Act)" should be present
    And the link should point to "https://www.irs.gov/businesses/corporations/fatca-related-forms"
    And clicking the link should open it in a new browser tab

  @Smoke @P0 @BDBP1-202 @JiraAC-10 @Navigation
  Scenario: Continue button navigates from Instruction Section to Personal Information
    Given the user is on the Instruction Section page
    When the user clicks the "Continue" button
    Then the user should be on the "Personal Information" step
    And the left sidebar should highlight "Personal Information" as the active step
    And the "Instructions" step should appear as completed

  # =============================================
  # FUNCTIONAL — ACCORDION CONTENT
  # =============================================

  @Functional @P0 @BDBP1-202 @JiraAC-06a @JiraAC-07 @Accordion
  Scenario: ECCU Territories accordion expands with correct identification requirements
    Given the user is on the Instruction Section page
    When the user clicks "Individual (National) of ECCU Territories"
    Then the accordion should expand
    And the "Identification" section should list one form of Government-Issued Picture ID
    And the accepted IDs should include "Passport", "National Identification Card", "Social Security Card", "Driver's License", "Voter's Card"
    And the "Residential Address" section should state "NO PROOF OF ADDRESS REQUIRED" for Saint Lucian Nationals
    And the "Additional Notes" section should include Minor account requirements
    And all other 3 accordion sections should remain collapsed

  @Functional @P0 @BDBP1-202 @JiraAC-06b @JiraAC-07 @Accordion
  Scenario: CARICOM accordion expands with correct dual-ID and address requirements
    Given the user is on the Instruction Section page
    When the user clicks "Resident Nationals of CARICOM (except ECCU territories)"
    Then the accordion should expand
    And the "Identification" section should require "Passport and Driver's License or National Identification Card"
    And the "Residential Address" section should list at least 6 valid proof-of-address documents
    And the residential address options should include "Original utility bill" dated within 3 months
    And "Additional Notes" should not be present for CARICOM

  @Functional @P0 @BDBP1-202 @JiraAC-06c @JiraAC-07 @Accordion
  Scenario: Non-Nationals accordion requires two forms of government-issued ID
    Given the user is on the Instruction Section page
    When the user clicks "Non-Nationals / Residents Outside CARICOM"
    Then the accordion should expand
    And the "Identification" section should require TWO forms of valid Government-Issued ID
    And the "Residential Address" section should list valid proof-of-address documents

  @Functional @P0 @BDBP1-202 @JiraAC-06d @JiraAC-07 @Accordion
  Scenario: Self-Employed accordion shows different ID requirements based on residency
    Given the user is on the Instruction Section page
    When the user clicks "Self – Employed Individuals"
    Then the accordion should expand
    And the "Identification" section should state 1 ID for ECCU/CARICOM nationals
    And the "Identification" section should state 2 IDs for Non-Nationals outside CARICOM
    And the "Residential Address" section should list valid proof-of-address documents

  @Functional @P1 @BDBP1-202 @JiraAC-03 @GeneralInstructions
  Scenario: General Instructions section displays all 4 mandatory bullet points and DISCLAIMER
    Given the user is on the Instruction Section page
    Then the "Instructions for completing the form" section should be visible
    And the section should contain exactly 4 bullet points
    And bullet 1 should state that the application must be completed in its entirety
    And bullet 2 should state no more than 4 persons on an account
    And a "DISCLAIMER" paragraph should be present in bold

  # =============================================
  # NEGATIVE SCENARIOS
  # =============================================

  @Negative @P0 @BDBP1-202 @Validation @ProductSelection
  Scenario: Clicking Continue without selecting any product shows a validation error
    Given the user is on the Select Product screen
    And no product has been selected
    When the user clicks "Continue"
    Then a validation message should be displayed: "Please select a product to continue."
    And the user should remain on the Select Product screen

  @Negative @P0 @BDBP1-202 @JiraAC-08 @Accordion @MutualExclusion
  Scenario Outline: Only one accordion can be open at a time
    Given the user is on the Instruction Section page
    And the "<first_accordion>" accordion is expanded
    When the user clicks "<second_accordion>"
    Then "<second_accordion>" should be expanded
    And "<first_accordion>" should be automatically collapsed

    Examples:
      | first_accordion                                          | second_accordion                                         |
      | Individual (National) of ECCU Territories                | Resident Nationals of CARICOM (except ECCU territories)  |
      | Resident Nationals of CARICOM (except ECCU territories)  | Non-Nationals / Residents Outside CARICOM                |
      | Non-Nationals / Residents Outside CARICOM                | Self – Employed Individuals                              |
      | Self – Employed Individuals                              | Individual (National) of ECCU Territories                |

  @Negative @P1 @BDBP1-202 @Accordion @DefaultState
  Scenario: No accordion content is visible on page load (all collapsed by default)
    Given the user has just arrived on the Instruction Section page
    Then all 4 accordion panels should be collapsed
    And no document requirement content should be visible without user interaction

  # =============================================
  # REGRESSION SCENARIOS
  # =============================================

  @Regression @P0 @BDBP1-202 @E2E @CoreFlow
  Scenario: End-to-end flow — Home to Instruction Section completes without errors
    Given the user is on the home page
    When the user clicks "Start Application"
    And the user selects "New Customer"
    And the user selects "Bank Accounts" then "Ordinary Savings"
    And the user clicks "Continue"
    Then the Instruction Section should load
    And the heading should show "Ordinary Savings Application"
    And there should be no JavaScript console errors during the flow

  @Regression @P0 @BDBP1-202 @JiraAC-09 @Accordion @AutoClose
  Scenario: Opening a new accordion automatically closes the previously open one
    Given the user is on the Instruction Section page
    When the user clicks "Individual (National) of ECCU Territories"
    Then "Individual (National) of ECCU Territories" should be expanded
    When the user clicks "Resident Nationals of CARICOM (except ECCU territories)"
    Then "Resident Nationals of CARICOM (except ECCU territories)" should be expanded
    And "Individual (National) of ECCU Territories" should be collapsed

  @Regression @P0 @BDBP1-202 @JiraAC-03 @DynamicContent @Salesforce
  Scenario: Product-specific instructions differ between Ordinary Savings and Loans
    Given the user navigates through the flow selecting "Loans" product
    When the user reaches the Instruction Section
    Then the heading should NOT say "Ordinary Savings Application"
    And the instruction content should be specific to the selected Loans product
    And the content should not be the same as the Ordinary Savings instructions

  # =============================================
  # REQUIREMENT GAP SCENARIOS
  # =============================================

  @Regression @P0 @BDBP1-202 @RequirementGap @JiraAC-DOD-03
  Scenario: Save Progress button is available on the Instruction Section
    Given the user is on the Instruction Section page
    Then a "Save Progress" button should be visible
    And clicking "Save Progress" should save the current application state
    And the user should be able to resume the application from the saved point

  @Regression @P0 @BDBP1-202 @RequirementGap @JiraAC-DOD-04
  Scenario: Back to Dashboard button is available on the Instruction Section
    Given the user is on the Instruction Section page
    Then a "Back to Dashboard" button should be visible
    And clicking "Back to Dashboard" should navigate the user to their dashboard

  # =============================================
  # SECURITY SCENARIOS
  # =============================================

  @Security @P1 @BDBP1-202 @ExternalLink @TabSecurity
  Scenario: FATCA link and all external links open in a new tab with noopener noreferrer
    Given the user is on the Instruction Section page
    When the user inspects all external hyperlinks on the page
    Then each external link should have target="_blank"
    And each external link should have rel="noopener noreferrer"
    And no sensitive application state should be exposed in the referrer header

  @Security @P1 @BDBP1-202 @URL @QueryParams
  Scenario: No PII or session tokens appear in the URL during the registration flow
    Given the user navigates through Home to Select Product to Instruction Section
    Then the URL should only contain "/SelfRegister" with no query parameters containing PII
    And no session tokens should be visible in the URL

  # =============================================
  # ACCESSIBILITY SCENARIOS
  # =============================================

  @Accessibility @P1 @BDBP1-202 @Keyboard @WCAG-2.1.1
  Scenario: All accordion buttons are keyboard accessible via Tab and Enter
    Given the user is on the Instruction Section page
    When the user navigates using Tab key only
    Then each accordion button should receive visible keyboard focus
    And pressing Enter on a focused accordion button should expand it
    And the Continue button should be reachable via keyboard

  @Accessibility @P1 @BDBP1-202 @ARIA @ScreenReader @WCAG-4.1.2
  Scenario: Accordion buttons have correct aria-expanded state
    Given the user is on the Instruction Section page
    Then all accordion buttons should have aria-expanded="false" initially
    When the user clicks "Individual (National) of ECCU Territories"
    Then that button should have aria-expanded="true"
    And all other accordion buttons should have aria-expanded="false"

  @Accessibility @P1 @BDBP1-202 @Zoom @WCAG-1.4.4
  Scenario: Instruction Section is fully usable at 200% browser zoom
    Given the user is on the Instruction Section page
    When the user sets browser zoom to 200%
    Then all 4 accordion buttons should remain visible and clickable
    And no horizontal scrollbar should appear
    And the "Continue" button should be fully visible and usable
