# Feature: User Login — Authentication
# Generated by: Generate Test Cases Skill (Playwright-Test-Planner)
# Application: [APP_URL]
# Generated on: 2026-05-16
# Coverage: Positive, Negative, Boundary, Security, Accessibility

Feature: User Login

  Background:
    Given the application is accessible at the base URL
    And the user is not authenticated

  # ==========================================
  # SMOKE / POSITIVE SCENARIOS
  # ==========================================

  @Smoke @P0 @Auth @Positive @Login
  Scenario: Successful login with valid credentials
    Given the user navigates to the login page
    When the user enters valid email "testuser@example.com"
    And the user enters valid password "SecurePass123!"
    And the user clicks the "Login" button
    Then the user should be redirected to the dashboard
    And the navigation header should display the user's name
    And no error messages should be visible

  @Smoke @P0 @Auth @Positive @Logout
  Scenario: Successful logout from authenticated session
    Given the user is logged in with valid credentials
    When the user clicks the user menu
    And the user clicks "Logout"
    Then the user should be redirected to the login page
    And the session should be cleared
    And navigating to the dashboard should redirect to login

  @Smoke @P0 @Auth @Positive @PageLoad
  Scenario: Login page displays all required elements on load
    Given the user navigates to the login page
    Then the email input field should be visible
    And the password input field should be visible
    And the "Login" button should be visible and enabled
    And the application logo should be displayed
    And the page should use HTTPS protocol

  # ==========================================
  # NEGATIVE SCENARIOS
  # ==========================================

  @Negative @P0 @Auth @InvalidCredentials
  Scenario Outline: Login fails with invalid credentials
    Given the user navigates to the login page
    When the user enters email "<email>"
    And the user enters password "<password>"
    And the user clicks the "Login" button
    Then an error message should be displayed
    And the error message should not reveal which field is wrong
    And the user should remain on the login page

    Examples:
      | email                    | password       |
      | testuser@example.com     | WrongPass123!  |
      | unknown@example.com      | SecurePass123! |
      | invalid@example.com      | wrongpassword  |

  @Negative @P0 @Auth @Validation @EmptyFields
  Scenario: Login fails when email field is empty
    Given the user navigates to the login page
    When the user leaves the email field empty
    And the user enters "SecurePass123!" in the password field
    And the user clicks the "Login" button
    Then a validation error should appear on the email field
    And the error message should say "Email is required"
    And no API request should be made

  @Negative @P0 @Auth @Validation @EmptyFields
  Scenario: Login fails when password field is empty
    Given the user navigates to the login page
    When the user enters "testuser@example.com" in the email field
    And the user leaves the password field empty
    And the user clicks the "Login" button
    Then a validation error should appear on the password field
    And the error message should say "Password is required"
    And no API request should be made

  @Negative @P1 @Auth @Validation @InvalidFormat
  Scenario Outline: Login fails with invalid email format
    Given the user navigates to the login page
    When the user enters "<invalid_email>" in the email field
    And the user enters "SecurePass123!" in the password field
    And the user clicks the "Login" button
    Then a validation error should appear: "Please enter a valid email address"
    And the form should not be submitted

    Examples:
      | invalid_email          |
      | plaintext              |
      | missing@domain         |
      | @nodomain.com          |
      | spaces in@email.com    |
      | double@@domain.com     |
      | email@                 |

  @Negative @P0 @Auth @Security @AccountLock
  Scenario: Account gets locked after 5 consecutive failed login attempts
    Given the user navigates to the login page
    When the user attempts to login with wrong password 5 consecutive times
    Then the account should be temporarily locked
    And the error message should indicate the account is locked
    And even correct credentials should fail during lockout period
    And an unlock notification email should be sent to the registered email

  @Negative @P1 @Auth @Session @Timeout
  Scenario: Session expires after configured inactivity period
    Given the user is logged in with valid credentials
    When the user is inactive for the configured session timeout period
    And the user attempts any authenticated action
    Then the user should be redirected to the login page
    And the message "Your session has expired. Please log in again." should appear

  # ==========================================
  # BOUNDARY VALUE SCENARIOS
  # ==========================================

  @Boundary @P2 @Auth @EmailField @MinBoundary
  Scenario: Login succeeds with minimum valid email length (6 characters)
    Given a user account exists with email "a@b.cc"
    When the user enters "a@b.cc" in the email field
    And the user enters the correct password
    And the user clicks Login
    Then the login should succeed
    And the user should reach the dashboard

  @Boundary @P2 @Auth @EmailField @MaxBoundary
  Scenario: Email field accepts maximum 254 characters
    Given the user navigates to the login page
    When the user attempts to enter 255 characters in the email field
    Then the field should enforce the 254-character maximum
    And input beyond the limit should be rejected or truncated

  @Boundary @P1 @Auth @PasswordField @MinBoundary
  Scenario: Login fails with password below minimum length (7 chars)
    Given the user navigates to the login page
    When the user enters "Pass12!" (7 characters) in the password field
    And the user clicks Login
    Then validation error should say "Password must be at least 8 characters"
    And the form should not be submitted

  # ==========================================
  # SECURITY SCENARIOS
  # ==========================================

  @Security @P0 @Auth @SQLInjection
  Scenario Outline: SQL injection in login fields does not authenticate
    Given the user navigates to the login page
    When the user enters "<sql_payload>" in the email field
    And the user enters "any_password" in the password field
    And the user clicks Login
    Then login should fail
    And no database error details should be exposed
    And the response should show a generic error message

    Examples:
      | sql_payload              |
      | ' OR '1'='1              |
      | admin'--                 |
      | '; DROP TABLE users;--   |
      | ' UNION SELECT 1,2,3--   |

  @Security @P0 @Auth @XSS
  Scenario Outline: XSS payloads in login fields do not execute
    Given the user navigates to the login page
    When the user enters "<xss_payload>" in the email field
    And the user clicks Login
    Then no JavaScript should execute
    And no alerts or popups should appear
    And the payload should be treated as literal text

    Examples:
      | xss_payload                          |
      | <script>alert('XSS')</script>        |
      | "><img src=x onerror=alert(1)>       |
      | <svg onload=alert(1)>                |

  @Security @P0 @Auth @Authorization @UnauthorizedAccess
  Scenario Outline: Unauthenticated access to protected pages redirects to login
    Given the user is not logged in
    When the user directly navigates to "<protected_url>"
    Then the user should be redirected to the login page
    And no authenticated content should be visible

    Examples:
      | protected_url     |
      | /dashboard        |
      | /profile          |
      | /admin            |
      | /settings         |
      | /reports          |

  @Security @P0 @Auth @Session @TokenInvalidation
  Scenario: Old session token is rejected after logout
    Given the user is logged in and the session token is captured
    When the user logs out
    And the user manually sets the old session token in the browser
    And the user navigates to a protected page
    Then the request should return 401 Unauthorized
    And no authenticated content should be accessible

  @Security @P0 @Auth @HTTPS
  Scenario: Login credentials are transmitted over HTTPS
    Given the user navigates to the login page
    When the user submits login credentials
    Then the login request should use HTTPS protocol
    And the password should NOT appear in the URL
    And the password should be sent in the POST request body

  @Security @P0 @Auth @RBAC
  Scenario: Regular user cannot access admin-only pages
    Given the user is logged in as a regular non-admin user
    When the user navigates directly to "/admin"
    Then the user should see a "403 Forbidden" or "Access Denied" message
    And no admin data should be displayed

  # ==========================================
  # ACCESSIBILITY SCENARIOS
  # ==========================================

  @Accessibility @P1 @Auth @Keyboard @WCAG-2.1-AA
  Scenario: Login form is fully operable with keyboard only
    Given the user navigates to the login page
    When the user uses Tab key to navigate to the email field
    And the user types a valid email
    And the user presses Tab to move to the password field
    And the user types a valid password
    And the user presses Tab to focus the Login button
    And the user presses Enter
    Then the login should succeed
    And no mouse interaction should be required

  @Accessibility @P1 @Auth @ScreenReader @WCAG-2.1-AA
  Scenario: Login form fields have proper ARIA labels for screen readers
    Given the user navigates to the login page
    Then the email field should have an associated label "Email"
    And the password field should have an associated label "Password"
    And required fields should have "aria-required=true"
    And the login button should have a descriptive accessible name

  @Accessibility @P1 @Auth @ErrorAnnouncement @WCAG-2.1-AA
  Scenario: Validation errors are announced by screen readers via ARIA live regions
    Given the user navigates to the login page
    When the user submits the form with empty fields
    Then validation errors should appear in an ARIA live region
    And each field error should be associated via "aria-describedby"
    And the errors should be announced without requiring manual focus

  @Accessibility @P1 @Auth @ColorContrast @WCAG-2.1-AA
  Scenario: Login page text meets WCAG AA color contrast ratio
    Given the user navigates to the login page
    Then all text elements should have a contrast ratio of at least 4.5:1
    And button text should have a contrast ratio of at least 4.5:1
    And placeholder text should have a contrast ratio of at least 4.5:1

  @Accessibility @P2 @Auth @Zoom @WCAG-2.1-AA
  Scenario: Login page is usable at 200% browser zoom
    Given the user navigates to the login page
    When the user zooms the browser to 200%
    Then all form elements should remain visible and accessible
    And no horizontal scroll bar should appear
    And the login flow should be completable at 200% zoom
